### ISSUE TITLE
[Feature Request] XML Rss?

### ISSUE THREAD

**Issue by ArcAIN6** [benji7425/discord-rss-feed#2]
Would it be possible to also allow the use of XML based RSS links? 

I have a small adult discord, and was wondering if it were possible to use porndig RSS links (i've tried, but it kills the bot)

example of their RSS link:
https://www.porndig.com/rss/top/videos.xml

Any help would be appreciated.

**Comment by benji7425** [comment]
Hi, sorry for not getting back to you sooner. RSS is XML anyway, so not entirely sure why you're having issues. There are a number of scaling issues I need to solve when I get the time, which may end up solving your particular problem at the same time, but am too busy at the moment to get these done. I have a [discord server](http://discord.gg/SSkbwSJ) you can join to get updates.

**Comment by ArcAIN6** [comment]
No rush, just a few feeds throw the exception

**Comment by benji7425** [comment]
Hey @ArcAIN6, apologies for how incredibly long it's been! I've had lots going on. Is this still something you would see value in?

**Comment by benji7425** [comment]
Closing due to lack of response, feel free to reopen if this is still an issue
